name: Build Trantor

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows:
    name: 'windows/msvc - ${{matrix.link}}'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        link: [ 'STATIC', 'SHARED' ]
    steps:
      - name: Checkout Trantor source code
        uses: actions/checkout@v2
        with:
          submodules: false

    - name: Create build directory
      run: |
        mkdir build

    - name: Create Build Environment & Configure Cmake SHARED
      shell: cmd
      working-directory: ./build
      if: ${{matrix.link}} == "SHARED" 
      run: |
        cmake .. \
        -DTRANTOR_USE_TLS=${{matrix.tls-provider}} \
        -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
        -DCMAKE_INSTALL_PREFIX=../install \
        -DUSE_SPDLOG=ON \
        -DBUILD_TESTING=ON \
        -DBUILD_SHARED_LIBS=ON

    - name: Create Build Environment & Configure Cmake STATIC
      shell: cmd
      working-directory: ./build
      if: ${{matrix.link}} == "STATIC"
      run: |
        cmake .. \
        -DTRANTOR_USE_TLS=${{matrix.tls-provider}} \
        -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
        -DCMAKE_INSTALL_PREFIX=../install \
        -DUSE_SPDLOG=ON \
        -DBUILD_TESTING=ON 

    - name: Build
      shell: cmd
      working-directory: ./build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        cmake --build .

    - name: Test
      working-directory: ./build
      shell: cmd
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ctest
